# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.srcs/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0.xci
# IP: The module: 'multiply_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.srcs/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0.xci
# IP: The module: 'multiply_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab3/lab3.gen/sources_1/bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
