# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/multiply/multiply.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: bd/multiply/ip/multiply_processing_system7_0_0/multiply_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_processing_system7_0_0 || ORIG_REF_NAME==multiply_processing_system7_0_0} -quiet] -quiet

# IP: bd/multiply/ip/multiply_multiply_0_0/multiply_multiply_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_multiply_0_0 || ORIG_REF_NAME==multiply_multiply_0_0} -quiet] -quiet

# IP: bd/multiply/ip/multiply_auto_pc_0/multiply_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_auto_pc_0 || ORIG_REF_NAME==multiply_auto_pc_0} -quiet] -quiet

# IP: bd/multiply/ip/multiply_ps7_0_axi_periph_0/multiply_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_ps7_0_axi_periph_0 || ORIG_REF_NAME==multiply_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/multiply/ip/multiply_rst_ps7_0_100M_0/multiply_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_rst_ps7_0_100M_0 || ORIG_REF_NAME==multiply_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/ugrads/c/cedarmaxwell/Documents/ECEN449/lab4/lab4.gen/sources_1/bd/multiply/multiply_ooc.xdc
